//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annonssystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ads
    {
        public int ads_ID { get; set; }
        public string ads_category { get; set; }
        public string ads_content { get; set; }
        public int ads_price { get; set; }
        public Nullable<long> ads_annonsor { get; set; }
    
        public virtual tbl_annonsorer tbl_annonsorer { get; set; }
    }
}
