//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annonssystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_annonsorer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_annonsorer()
        {
            this.tbl_ads = new HashSet<tbl_ads>();
        }
    
        public long an_ID { get; set; }
        public Nullable<bool> an_corp { get; set; }
        public string an_name { get; set; }
        public string an_srName { get; set; }
        public string an_adr { get; set; }
        public Nullable<int> an_poCode { get; set; }
        public string an_city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ads> tbl_ads { get; set; }
    }
}
